kind: pipeline
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: beanjs/hw-build-env
      registry: https://hub.docker.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: 
        - latest


  - name: notify
    image: beanjs/drone-wxpusher
    settings:
      ids: 
        from_secret: uid
      title: |
        项目名称：${DRONE_REPO_NAME}
        项目地址：${DRONE_GIT_HTTP_URL}
      remark: |
        分支：${DRONE_BRANCH}
        ${DRONE_COMMIT_MESSAGE} 
    